In [75]:
import pandas as pd 
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [44]:
data = pd.read_csv("smartphone_clained")
data = data.drop("Unnamed: 0",axis=1)

In [45]:
num_col = data.drop(['Marque', 'Model', 'couleur', 'os', 'CPU', 'Resolution_ecran', 'camera','Bluetooth'],axis=1)
num_col

Battery(mAh)  Taille_ecran(en pouces) Réseau  Stockage(Go)  RAM(Go)  \
0          3700.0                      6.1    5G          128.0      8.0   
1          5020.0                      6.6    4G          128.0      6.0   
2          4500.0                      6.4    5G          128.0      8.0   
3          5000.0                      6.5    5G           64.0      4.0   
4          5330.0                      6.7    4G          128.0      4.0   
..            ...                      ...    ...           ...      ...   
786        2815.0                      6.1    5G          512.0      6.0   
787        2815.0                      6.1    5G          512.0      6.0   
788        2815.0                      6.1    5G         1000.0      6.0   
789        2815.0                      6.1    5G         1000.0      6.0   
790        2815.0                      6.1    5G         1000.0      6.0   

     nb_capteur_ph  Selfie(mégapixels)  Price(€)  
0              3.0                10.0     749.0  
1              4.0                16.0     249.0  
2              3.0                16.0     419.0  
3              3.0                 8.0     299.0  
4              4.0                 8.0     229.0  
..             ...                 ...       ...  
786            3.0                12.0    1620.0  
787            3.0                12.0    1620.0  
788            3.0                12.0    1908.0  
789            3.0                12.0    1908.0  
790            3.0                12.0    1908.0  

[791 rows x 8 columns]

In [46]:
L = num_col['Réseau'].str.split("G",expand =True)
num_col.insert(2, 'Réseau(G)', L[0])
num_col.drop('Réseau',axis=1,inplace=True)
num_col['Réseau(G)'] = num_col['Réseau(G)'].astype('float')

In [47]:
num_col.isna().sum()

Battery(mAh)                 1
Taille_ecran(en pouces)      0
Réseau(G)                    0
Stockage(Go)                 0
RAM(Go)                      0
nb_capteur_ph              217
Selfie(mégapixels)         218
Price(€)                     0
dtype: int64

In [48]:
num_col[num_col['Battery(mAh)'].isna() == True]

Battery(mAh)  Taille_ecran(en pouces)  Réseau(G)  Stockage(Go)  RAM(Go)  \
702           NaN                      5.4        5.0         128.0      4.0   

     nb_capteur_ph  Selfie(mégapixels)  Price(€)  
702            2.0                12.0     664.0

In [49]:
num_col = num_col.drop(num_col[num_col['Battery(mAh)'].isna() == True].index)

In [50]:
X = num_col.drop(['nb_capteur_ph','Selfie(mégapixels)'],axis=1)
y = num_col['nb_capteur_ph'] 
# Division des données en ensembles d'apprentissage et de test
y_train = y[y.isna() == False]
X_train = X.loc[y_train.index,]
X_test = X.loc[y[y.isna() == True].index,]
y_test = y[y.isna() == True]
dtc = DecisionTreeClassifier()
dtc.fit(X_train, y_train)
# Prédiction des classes pour les données de test
y_pred = dtc.predict(X_test)
y_pred

array([2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2., 2., 2., 2., 3., 1.,
       1., 2., 2., 1., 1., 1., 1., 2., 3., 3., 1., 3., 1., 3., 3., 3., 3.,
       3., 2., 4., 3., 3., 3., 3., 4., 3., 1., 3., 3., 3., 4., 3., 3., 4.,
       4., 3., 2., 4., 4., 4., 4., 4., 4., 4., 3., 3., 4., 4., 4., 4., 4.,
       3., 3., 3., 2., 3., 3., 4., 4., 3., 3., 3., 4., 3., 4., 4., 4., 4.,
       3., 3., 3., 3., 3., 3., 3., 2., 3., 4., 3., 2., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 1., 2., 1., 2., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 2., 1., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 3., 1., 2., 1., 2., 3., 1., 3., 3., 2., 1.,
       3., 2., 3., 3., 2., 2., 3., 3., 2., 1., 1., 2., 2., 3., 3., 3., 2.,
       2., 3., 1., 3., 3., 3., 4., 2., 3., 4., 2., 3., 3., 4., 4., 2., 2.,
       2., 4., 4., 1., 3., 4., 3., 4., 4., 1., 4., 3., 3., 3., 3., 3., 2.,
       3., 4., 4., 3., 3., 4., 3., 1., 4., 1., 3., 3., 3.])

In [51]:
num_col['nb_capteur_ph'][num_col['nb_capteur_ph'].isna() == True] = y_pred

In [52]:
X = num_col.drop('Selfie(mégapixels)',axis=1)
y = num_col['Selfie(mégapixels)'] 
# Division des données en ensembles d'apprentissage et de test
y_train = y[y.isna() == False]
X_train = X.loc[y_train.index,]
X_test = X.loc[y[y.isna() == True].index,]
y_test = y[y.isna() == True]
dtc = DecisionTreeRegressor()
dtc.fit(X_train, y_train)
# Prédiction des classes pour les données de test
y_pred = dtc.predict(X_test)

In [53]:
num_col['Selfie(mégapixels)'][num_col['Selfie(mégapixels)'].isna() == True] = y_pred

In [54]:
num_col.isna().sum()

Battery(mAh)               0
Taille_ecran(en pouces)    0
Réseau(G)                  0
Stockage(Go)               0
RAM(Go)                    0
nb_capteur_ph              0
Selfie(mégapixels)         0
Price(€)                   0
dtype: int64

In [55]:
num_col

Battery(mAh)  Taille_ecran(en pouces)  Réseau(G)  Stockage(Go)  RAM(Go)  \
0          3700.0                      6.1        5.0         128.0      8.0   
1          5020.0                      6.6        4.0         128.0      6.0   
2          4500.0                      6.4        5.0         128.0      8.0   
3          5000.0                      6.5        5.0          64.0      4.0   
4          5330.0                      6.7        4.0         128.0      4.0   
..            ...                      ...        ...           ...      ...   
786        2815.0                      6.1        5.0         512.0      6.0   
787        2815.0                      6.1        5.0         512.0      6.0   
788        2815.0                      6.1        5.0        1000.0      6.0   
789        2815.0                      6.1        5.0        1000.0      6.0   
790        2815.0                      6.1        5.0        1000.0      6.0   

     nb_capteur_ph  Selfie(mégapixels)  Price(€)  
0              3.0                10.0     749.0  
1              4.0                16.0     249.0  
2              3.0                16.0     419.0  
3              3.0                 8.0     299.0  
4              4.0                 8.0     229.0  
..             ...                 ...       ...  
786            3.0                12.0    1620.0  
787            3.0                12.0    1620.0  
788            3.0                12.0    1908.0  
789            3.0                12.0    1908.0  
790            3.0                12.0    1908.0  

[790 rows x 8 columns]

### feature selection : Variance threshold

In [56]:
from sklearn.feature_selection import VarianceThreshold  
from sklearn.feature_selection import VarianceThreshold
import numpy as np
# instantiate a variance threshold feature selector
selector = VarianceThreshold(threshold=0.2)
# fit the selector to the data
selector.fit(num_col)

VarianceThreshold(threshold=0.2)

In [57]:
# get the indices of the selected features
selected_features = selector.get_support()
selected_features

array([ True, False,  True,  True,  True,  True,  True,  True])

In [58]:
concol = [column for column in num_col.columns 
          if column not in num_col.columns[selected_features]]
concol2 = [column for column in num_col.columns 
          if column  in num_col.columns[selected_features]]
print("selected_features : ")
for features in concol2:
    print(features)
print("/n unselected_features :")
for features in concol:
    print(features)

selected_features : 
Battery(mAh)
Réseau(G)
Stockage(Go)
RAM(Go)
nb_capteur_ph
Selfie(mégapixels)
Price(€)
/n unselected_features :
Taille_ecran(en pouces)


#### On remarque que la colonne 'Taille_ecran(en pouces)' est celle à supprimer

In [59]:
from sklearn.feature_selection import SelectKBest, f_regression
# Select the best k features using SelectKBest method
selector = SelectKBest(f_regression, k=5)
selected_features = selector.fit_transform(num_col,y)

In [60]:
mask = selector.get_support()
# Use the mask to select only the selected features from the original dataset
selected_feature_names = num_col.columns[mask]
# Show the selected features
print("Selected features:")
print(selected_feature_names)

Selected features:
Index(['Réseau(G)', 'RAM(Go)', 'nb_capteur_ph', 'Selfie(mégapixels)',
       'Price(€)'],
      dtype='object')


In [61]:
num_col = num_col.drop('Taille_ecran(en pouces)',axis=1)

In [63]:
num_col

Battery(mAh)  Réseau(G)  Stockage(Go)  RAM(Go)  nb_capteur_ph  \
0          3700.0        5.0         128.0      8.0            3.0   
1          5020.0        4.0         128.0      6.0            4.0   
2          4500.0        5.0         128.0      8.0            3.0   
3          5000.0        5.0          64.0      4.0            3.0   
4          5330.0        4.0         128.0      4.0            4.0   
..            ...        ...           ...      ...            ...   
786        2815.0        5.0         512.0      6.0            3.0   
787        2815.0        5.0         512.0      6.0            3.0   
788        2815.0        5.0        1000.0      6.0            3.0   
789        2815.0        5.0        1000.0      6.0            3.0   
790        2815.0        5.0        1000.0      6.0            3.0   

     Selfie(mégapixels)  Price(€)  
0                  10.0     749.0  
1                  16.0     249.0  
2                  16.0     419.0  
3                   8.0     299.0  
4                   8.0     229.0  
..                  ...       ...  
786                12.0    1620.0  
787                12.0    1620.0  
788                12.0    1908.0  
789                12.0    1908.0  
790                12.0    1908.0  

[790 rows x 7 columns]

### Utiliser l'algorithme de l'arbre de décision pour prédire la valeur du prix

In [66]:
X = num_col.drop('Price(€)',axis=1)
y = num_col['Price(€)'] 

In [67]:
# Division des données en ensembles d'apprentissage et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [68]:
dtc = DecisionTreeRegressor()

In [69]:
# Apprentissage du modèle
dtc.fit(X_train, y_train)

DecisionTreeRegressor()

In [70]:
# Prédiction des classes pour les données de test
y_pred = dtc.predict(X_test)

In [71]:
y_pred

array([ 339.9875    ,  899.        ,  121.90727273,  122.        ,
       1099.        ,  149.        ,  339.9875    ,  143.85714286,
        177.75      ,  271.66666667,  899.        ,  177.75      ,
       1199.        ,  589.        ,  175.98      ,  461.        ,
        278.714     ,  515.72      ,  306.34      ,  413.83333333,
        799.        ,  899.975     ,  382.95      ,  318.27      ,
        216.39      ,  385.06666667,  382.95      ,  778.83333333,
        469.        ,  163.        ,  332.5       , 1049.        ,
        143.85714286,  513.        ,  778.83333333,  513.        ,
        185.985     ,  187.635     ,  291.33333333,  214.04      ,
        955.9       ,  269.1       ,  729.        ,  236.7       ,
        437.84428571,  336.82666667,  431.29833333,  778.83333333,
        162.45      ,  342.45      ,  634.        ,  686.        ,
        413.83333333,  589.        ,  467.        , 1207.99666667,
        640.85714286, 1119.        ,  209.        ,  271.66666

In [76]:
# Calculer le RMSE
rmse = mean_squared_error(y_test, y_pred, squared=False)
print('RMSE:', rmse)

# Calculer le R²
r2 = r2_score(y_test, y_pred)
print('R²:', r2)

RMSE: 146.9470826628099
R²: 0.8804929591372773
